### ISSUE TITLE
Some keys not works

### ISSUE THREAD

**Issue by jiripolacek** [Lord-Kamina/keybinder#10]
Hi,

there is a lot of keys (keycodes) which doesn't work in Keybinder and worked in Customizable Shortcuts:

VK_MEDIA_NEXT_TRACK (0xB0)
VK_MEDIA_PREV_TRACK (0xB1)
VK_MEDIA_STOP (0xB2)
VK_BROWSER_BACK (0xA6)
VK_BROWSER_FORWARD (0xA7)
VK_BROWSER_FAVORITES (0xAB)
VK_LAUNCH_APP2 (0xB7)

When I click that keys in Mapping>Change, it does nothing. When I put them in store.json code instead of VK_ESC etc. - they do nothing too.

In Customizable Shortcuts store.json I have:

`{"overlays_v2":{"goBackKb":{"modifiers":0,"key":"BrowserFavorites"},"goForwardKb":{"modifiers":0,"key":"LaunchApplication2"},"key_undoCloseTab":{"modifiers":0,"key":"MediaTrackPrevious"},"key_stop":{"disabled":true},"key_close":{"modifiers":0,"key":"Escape"},"key_switchToPrevTab":{"modifiers":0,"key":"BrowserBack"},"key_switchToNextTab":{"modifiers":0,"key":"BrowserForward"},"key_newNavigatorTab":{"modifiers":0,"key":"MediaTrackNext"},"key_viewSource":{"modifiers":0,"key":"MediaPlayPause"}}}`

Can you please fix it? (Or how to do it this keys/keycodes works?)

Lots of keyboard have this keys and it is really timesaver to programme them for custom shortcuts.

Thanks a lot.

Jiri

**Comment by Lord-Kamina** [comment]
I'll look into it, for sure.

-- 
Gregorio Litenstein Goldzweig
[image: glit_ind.png]
Médico Cirujano



   - Fono: +56 9 96343643 <+56%209%2096343643>
   - E-Mail: g.litenstein@gmail.com

**Comment by jolange** [comment]
German umlauts (ä, ö, ü) also do not work (they did in Customizable Shortcuts). When pressing them while setting a shortcut, they are not recognized at all.

I'm not sure if it's the same problem or a separate issue.

**Comment by Lord-Kamina** [comment]
I'll see what I can do. How do you do those umlauts? (I'm familiar with how they're done in a Spanish keyboard, don't know others)  

I've recently made some changes to the way keys are read for the version I'm working on but I don't know whether that will fix it. There are some limitations in the way keys are read that I doubt I'll be able to get around anytime soon.

**Comment by jolange** [comment]
They are keys on their own in german keyboard layouts (that's why I'd like to bind them), see for example [here](https://upload.wikimedia.org/wikipedia/commons/3/36/KB_Germany.svg).

If I'll find the time, I can also look into this. If you have a good idea where to start, any hint could be useful!

**Comment by Lord-Kamina** [comment]
I'll try it out later with the new version and let you know.

**Comment by Lord-Kamina** [comment]
I tried those keys under a German keyboard and they should work. Not however, that they will only work in keyboards where they don't function as a dead key.

I still have to see what I can do re:Media keys

**Comment by Lord-Kamina** [comment]
I have changed the way keys are parsed, so at least Dead keys should now be working. Cannot be certain about media keys since they don't exist on Mac (and I don't have any keyboards that have them, anyway)

This should be fixed by 2f1852532992c013f54510169c7378819df8efd5. It won't show on AMO for a while yet, due to the review process, but you can try it out in the releases page.

**Comment by jolange** [comment]
@Lord-Kamina I just installed it and it works perfectly! Thanks for your efforts!
