### ISSUE TITLE
Missing "Search" keyboard shortcuts

### ISSUE THREAD

**Issue by Aralun** [Lord-Kamina/keybinder#13]
Comparing the Keybinder `Shortcut Mappings` dialogue and [this official list](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_search), the following shortcuts are missing:

| Command | Shortcut key | Context |
| :-- | :-- | :-- |
| Quick-find within link-text only | <kbd>'</kbd> |  |
| Quick-find | <kbd>/</kbd> |  |
| Close the find or quick-find bar | <kbd>Esc</kbd> | \- when the Find or Quick Find bar is focused |
| Quickly switch between search engines | <kbd>Alt</kbd> + <kbd>↑</kbd> <br/>   <kbd>Alt</kbd> + <kbd>↓</kbd> | \- when Search Bar is focused |
| View menu to switch, add or manage search engines | <kbd>Alt</kbd> + <kbd>↑</kbd> <br/>   <kbd>Alt</kbd> + <kbd>↓</kbd> <br/> <kbd>F4</kbd> | \- when Search Bar is focused |

The first bullet is particularly troublesome as the `'` default quick-find within link shortcut key is actually on the "4" for an [Azerty keyboard](https://en.wikipedia.org/wiki/AZERTY).

**Comment by Lord-Kamina** [comment]
I don't think those shortcuts can be changed or disabled, at least not with
the current approach and most likely not with any approach that doesn't
involve rewriting almost the entire addon. The way it works is it scans
browser windows for any shortcuts defined via XUL. I think the ones you
mention are  hard-coded. However, I'm working on a feature to define custom
xul keys that can then be remapped. Perhaps that might work? Haven't really
tried.
