### ISSUE TITLE
Shortcuts always get reset automatically

### ISSUE THREAD

**Issue by Keith94** [Lord-Kamina/keybinder#19]
I noticed many cases where all my custom or disabled shortcuts are completely reset to default.

I think the issue may be caused by Firefox crashing, or it's because I always force quit Firefox using a hotkey combination (via [EmergencyExit](https://github.com/emoose/EmergencyExit)), or they are simply lost between sessions?

Is there some other debug information I can provide?

**Comment by Lord-Kamina** [comment]
If I had to wager I'd put my money on emergency exit. Although certainly it
could also be a bug. Console logs are often useful in those cases

**Comment by Keith94** [comment]
Well the program seems to be equivalent to killing Firefox in Task Manager... but seems like after enough restarts or enough time goes by then the shortcuts are reset. I need to investigate more.

**Comment by Lord-Kamina** [comment]
This should be fixed by 2f1852532992c013f54510169c7378819df8efd5. It won't show on AMO for a while yet, due to the review process, but you can try it out in the releases page.

**Comment by Keith94** [comment]
I wish it was... just restarted my PC and all shortcuts are reset again :(

I will do more testing in another profile.. where are shortcut settings saved exactly?

**Comment by Lord-Kamina** [comment]
In 2.0.0, they're stored in `extensions.keybinder@fail.cl.keybinderOverlays`; in previous versions they were located in your profile, under "jetpack" folder. I'm utterly unable to reproduce your issue.

... there is definitely something wrong with your setup... I'll try EmergencyExit out and see if that's it, because I've tested numerous setups and so far, nada.

**Comment by Lord-Kamina** [comment]
In fact, if I open about:config and search for Keybinder, I can see the preferences change in real time when I change something in the shortcuts menu.

**Comment by Keith94** [comment]
I've been using the add-on in a new profile - haven't run into this issue so far, so assuming it's resolved.
