### ISSUE TITLE
Apply shortcut settings to specific sites

### ISSUE THREAD

**Issue by dotnetdan** [Lord-Kamina/keybinder#2]
Hi, just wondering is it possible to apply shortcut settings only to specific sites?  If not, I'd suggest it as a feature.  It's very useful for disabling browser shortcuts on certain webapps, especially browser based remote desktop like MYPC.  Thanks!

**Comment by Lord-Kamina** [comment]
No, it's not currently possible to do this. I'm not really familiar with the MYPC remote desktop, so I have no idea whether it'd be feasible or not.

I'll consider it in the future but I'm not sure it can be done in a neat way.

**Comment by Lord-Kamina** [comment]
Referenced wrong issue on that commit.
