### ISSUE TITLE
THE EVENT IS WORKING

### ISSUE THREAD

**Issue by impman** [Lord-Kamina/keybinder#21]
Uhh, today the program updated and anytime I have flash loaded on a page I'll get regular window popups that say "THE EVENT IS WORKING". I've doublechecked it's Keybinder by disabling all other addons and toggling it on or off.

Using Firefox, downloaded directly from the Mozilla Addons page.

**Comment by Lord-Kamina** [comment]
It's a known issue, and in fact the latest commit fixes this; I
accidentally forgot to comment out a debug statement in a content script.
The way to get around it for now is to disable the "Steal focus fron
plugins" option.

-- 
Gregorio Litenstein Goldzweig
[image: glit_ind.png]
Médico Cirujano



   - Fono: +56 9 96343643 <+56%209%2096343643>
   - E-Mail: g.litenstein@gmail.com
