### ISSUE TITLE
Make shortcuts list resize vertically on window resize

### ISSUE THREAD

**Issue by krem** [Lord-Kamina/keybinder#22]
Shortcut mappings list won't resize vertically even when you maximize window vertically, which is annoying to scroll more than in resized list.

**Comment by Lord-Kamina** [comment]
How are you even resizing the window? It's supposed to be a fixed size!

What OS are you using?

**Comment by krem** [comment]
Linux Mint, it's window manager resizes such windows. Anyway if window will be resizable along with list of mappings - it would be a big relief. Thanks for your work.
