### ISSUE TITLE
Key binding for Backquote_Key not persisting

### ISSUE THREAD

**Issue by HasaniM** [Lord-Kamina/keybinder#23]
I am trying to assign **Control + ²** (squared) key on my "azerty" keyboard, (the key above the tab button) to the action **Switch to the Next Tab group**.
When I edit the shortcut, and press the key combo, it is detected as the shortcut **Control + Backquote_Key** and is assigned successfully to the action.
For as long as Firefox is active, this shortcut works correctly, and is shown correctly in the shortcuts list.
However, when I close Firefox, and open it again, I can see that the shortcut for this button was not stored correctly. In the shortcuts list, it is now shown as **Control + undefined_Key** instead...
I also assigned a different key to the action **Switch to Previous Tab Group** (**Ctrl + Shift + <**),
and this works, and keeps working even after a restart of Firefox. So the issue is not in being able to save anything, but seems specific to that **²**-button...
FYI: I'm still on Firefox 44 (company policy), on Ubuntu 16.04, using a Belgian azerty keyboard with Keybinder 2.0.3

**Comment by Lord-Kamina** [comment]
For starters, let me see if I can replicate the issue, and I'll get back to
you.

**Comment by Lord-Kamina** [comment]
Mind giving me some more details on your AZERTY layout? Is it French, Arabic, or something else altogether? According to the API documentation, the method I'm using now should be locale-agnostic, but that clearly doesn't seem to be the case so I'll need to do some extensive testing, it appears.

**Comment by HasaniM** [comment]
I had to look it up on wikipedia myself :-)
Apperently there are 2 main variants of AZERTY keyboards, the French and the Belgian,
and I'm using the Belgian variant.
The button that I want to use, is for the "²" in both layouts, but for the Belgian variant,
in combination with the SHIFT-key you get "³". But I don't think that makes a difference here,
since I don't use the Shift-key for my shortcut...

**Comment by Lord-Kamina** [comment]
Hmm. I think the only way to fix this will be to migrate to a completely
locale-agnostic implementation. Something that's puzzling me though, is
that key should he "IntlBackslash_Key", not "Backquote_Key"

**Comment by HasaniM** [comment]
No idea about the implementation, but I think that the button that has the "²" in (Belgian)AZERTY,
is the same button than the "`" in QWERTY. (The one above the TAB button)
So when you say that you used a locale-agnostic implementation, and I press
that key, to me it seems fine that it is detected as the "Backquote_key", no?

**Comment by Lord-Kamina** [comment]
2.0.4 is now live and should fix this issue, please test it and report.

**Comment by HasaniM** [comment]
I just installed the 2.0.4 version, and everything now seems to be working as it should.
I restarted Firefox 3 times, switching to a different shortcut, in between, but it works like a charm!!
So for me, this issue is solved, and can be closed.
Thanks!
