### ISSUE TITLE
Buggy on Debian sid

### ISSUE THREAD

**Issue by MicroBeast** [Lord-Kamina/keybinder#28]
After installation:
The list is empty. It does show once, but can't do a thing on it. 
Keybinder window can not be close. It become always on top empty window. Need to kill Firefox to close it.

My spec:
Debian sid amd64
Firefox 50.0.0 ~ 50.1.0 (either official and Debian package).

Tested on:
Window Manager Openbox.
Desktop Environment XFCE 4.
Clean Firefox profile with this add-on only.

Thanks.

**Comment by Lord-Kamina** [comment]
Could you try running it from the commandline and giving me a dump of the
console/any errors? I'm afraid I don't have access to any debian machines.

**Comment by MicroBeast** [comment]
Nothing interesting, only got these:

```
1482972711482	addons.webextension.{72b2e02b-3a71-4895-886c-fd12ebe36ba3}	WARN	Loading extension '{72b2e02b-3a71-4895-886c-fd12ebe36ba3}': Reading manifest: Error processing permissions.5: Unknown permission "management"
1482972711484	addons.webextension.{72b2e02b-3a71-4895-886c-fd12ebe36ba3}	WARN	Loading extension '{72b2e02b-3a71-4895-886c-fd12ebe36ba3}': Reading manifest: Error processing author: An unexpected property was found in the WebExtension manifest.
1482972711551	addons.webextension.{72b2e02b-3a71-4895-886c-fd12ebe36ba3}	WARN	Please specify whether you want browser_style or not in your browser_action options.
1482972711703	addons.webextension.firefox@tampermonkey.net	WARN	Please specify whether you want browser_style or not in your browser_action options.
tabs.onRemoved event fired after context unloaded.
tabs.onRemoved event fired after context unloaded.
tabs.onRemoved event fired after context unloaded.
tabs.onRemoved event fired after context unloaded.
tabs.onRemoved event fired after context unloaded.
tabs.onRemoved event fired after context unloaded.
tabs.onRemoved event fired after context unloaded.
tabs.onRemoved event fired after context unloaded.
tabs.onUpdated event fired after context unloaded.
tabs.onUpdated event fired after context unloaded.
```
Of course those two addons warning didn't show up on clean profile.

**Comment by Lord-Kamina** [comment]
Weird. I'll try tomorrow with ubuntu and see if it works, perhaps that
could give me an approximation to the issue.

**Comment by MicroBeast** [comment]
Indead it's weird. No error found anywhere, not even in FF Browser Console (--jsconsole), xsession-error, or any other usual error logs.

One thing. After Firefox restart the list does populate, and seem I could change anything. Open-Close this addon setting window approx. 5 times, empty and can't be close again. Not tested if this addon actually do its jobs.

Tried to change GTK3 widget theme to any other GTK3 themes, no luck either.

**Comment by ian-kelling** [comment]
fyi: I'm on debian testing. It's working fine for me. windows manager is xmonad, no desktop environment. Firefox package version 50.1.0-1.

**Comment by Lord-Kamina** [comment]
Good, because I still haven't been able to get around to getting a debian live usb, and am currently working on a place with 256 kbps internet in the middle of the desert.

**Comment by MicroBeast** [comment]
Ah, you guys are right; it is work now. `Keybinder` was turned off since I report the problem.
I'm wondering what's going on here. My rough sum: System Libraries.
Since the time of my report the usual culprit like `Xorg`, `NVidia proprietary`, `GTK+` & `libc` had been updated at least once on sid.

I believe you can mark this solved then.
**Thank you** Lord-Kamina & ian-kelling.

**Comment by ian-kelling** [comment]
> My rough sum: System Libraries.

I agree, that seems likely. Feel free to close this.
