### ISSUE TITLE
Ctrl+Alt recognized as AltGraph

### ISSUE THREAD

**Issue by Keith94** [Lord-Kamina/keybinder#29]
For some reason using Control + Alt in a shortcut is recognized as "AltGraph" by Keybinder. However the reader mode native shortcut displays the correct "Control + Alt" by default. Shouldn't it be made consistent?

![firefox_2016-12-29_08-26-22](https://cloud.githubusercontent.com/assets/5490615/21548349/a6c5ae2a-cda0-11e6-85f4-3199367f0b3c.png)

**Comment by Lord-Kamina** [comment]
It's because in Windows Control + Alt is the same as AltGraph (try it), but
the other shortcut is most likely appearing as Control + alt due to a
variation in how it's defined or something. This is mostly a cosmetic
issue.
