### ISSUE TITLE
Mapping copy, cut, paste to ALT + doesn't work

### ISSUE THREAD

**Issue by jakeyeung** [Lord-Kamina/keybinder#3]
I tried remapping shortcuts from CTRL+ to ALT+ and many of the commands work, such as New Tab, Select Al, and Find.  

However, COPY, CUT, and PASTE, does not seem to work. I have tried mapping CUT to ALT + X, ALT + B ALT, ALT + I, but it does not seem to work. CTRL + X still works, however.

**Comment by Lord-Kamina** [comment]
I managed to reproduce this and it would seem mapping them to any other modifier does not work. I am looking into it and will try fixing it soon.
