### ISSUE TITLE
'Shortcut mappings' button no longer works (Windows, Firefox 53.0.2 64-bit)

### ISSUE THREAD

**Issue by ghost** [Lord-Kamina/keybinder#39]
The Shortcut mappings button, which is the main point of this extension, no longer does anything, I am sad to say.

**Comment by Lord-Kamina** [comment]
I'm very sorry but after much raging I've decided to cease maintaining the addon (you might find a small note why in the README in the main tree)... In fact, I've switched from Firefox altogether. Deprecation of XUL and addon-SDK while not even adopting all WebExtension APIs (and a buggy-as-fuck multiprocess, to boot) is kind of a buzzkill to me. I've moved to Vivaldi, which is also a Chrome fork but with additions to make it more similar to the Opera of old, with a big emphasis on customization. It has built-in support for shortcut mapping, I suggest you try it out.

**Comment by ghost** [comment]
Understood. Thank you.
