### ISSUE TITLE
Trying to disable / but there's no entry for that 

### ISSUE THREAD

**Issue by xenithorb** [Lord-Kamina/keybinder#4]
I installed this extension in order to disable '/' displaying the quick find toolbar. This extension doesn't yet seem to be able to disable that.

**Comment by Lord-Kamina** [comment]
That is most likely a second shortcut for the same action associated to Control/Command+F, I'll look into it.

**Comment by xenithorb** [comment]
It may be (you'd know the inner-working of how they're bound better than I) but the displayed toolbars have different functionality. 

The '/' one is really a one-off search and doesn't display all of the functionality that CTRL+F does. 

I'm trying to disable it because one of my favorite media players uses '/' for start/stop unfortunately. (Probably a chrome developer)

**Comment by Lord-Kamina** [comment]
I'm afraid it's not possible to do it. The "/" is processed by a completely different handler than most other commands/hotkeys. I made a small patch to create an actual key to make it behave like the rest of the shortcuts my extension manages, and by doing this it is possible to create an additional shortcut for that search, but it cannot be disabled.
