### ISSUE TITLE
What does "score" mean?

### ISSUE THREAD

**Issue by cshaa** [Lord-Kamina/keybinder#42]
In `keybinder.properties` there is a line saying:
```
NewCustomXulInvalid.text= Use only letters, numbers, score and underscore.
```

I googled a lot and I couldn't find what *score* means in this context. Is it a hyphen?
(I need this for the Czech translation).

**EDIT:** In Spanish its's translated as a *guión*, so I guess it *is* a hyphen.

**Comment by Lord-Kamina** [comment]
Yeah. Might have been an error on my part.

P.S. As cool as it is that you're translating it to Czech, you should be
warned it's sort of an exercise in futility, considering a couple of
versions from now, the extension will be rendered completely useless by
Mozilla's self-destruct course.

**Comment by m93a** [comment]
No problem, it took me less than an hour
