### ISSUE TITLE
Issue with http://comicskingdom.com games

### ISSUE THREAD

**Issue by FredMcD-HotMail** [Lord-Kamina/keybinder#8]
I play games and Keybinder is causing a problem. I go to the page of the game
I want to play. The game opens in a small separate window. But the game
in the window keeps loosing focus. Disabling Keybinder ends the problem.

**Comment by Lord-Kamina** [comment]
Have you made sure the "Steal focus from plug-ins" option is turned off? If it's not, turn it off an check whether it solves your problem. If it does, please fix your review.

**Comment by FredMcD-HotMail** [comment]
Thank you. I turned that option off and all is well.
