### ISSUE TITLE
Shortcut changes not shown in menues

### ISSUE THREAD

**Issue by roaldandresen** [Lord-Kamina/keybinder#9]
Hi
It seems that the shortcut changes do not change the text in the menues.  E.g. I changed "New Tab" to Ctrl+N.  This works great, but the File menu still shows "New Tab Ctrl+T".
It's not something that troubles me, but it may trouble someone else.
Great plug-in btw. - a "must have" after Mozilla disabled Tauberts plug-in.

**Comment by Lord-Kamina** [comment]
Thanks and very glad you like it. This is a known issue that I don't plan to fix anytime soon. The reason is changing it would necessitate a tremendous change to the code, a much larger memory footprint and in the end it would all just be cosmetic.
